### ISSUE TITLE
Strange UI appearance on Ubuntu 19.10

### ISSUE THREAD

**Issue by msekmfb** [krlvm/PowerTunnel#12]
I've been using PowerTunnel for four months on Ubuntu 19.10 and just noticed strange colors in UI after after long non-use:
![screen-130520](https://user-images.githubusercontent.com/59621052/81816265-c4739000-9533-11ea-8186-40d7fe12f74e.png)

**Comment by krlvm** [comment]
There's an issue with GNOME Desktop Environment.
What version of JRE you're running?

**Comment by msekmfb** [comment]
I updated from version 8 to 11 yesterday.
I've noticed an another UI issue - app bar name is invalid
![screen-130520-2](https://user-images.githubusercontent.com/59621052/81817562-91320080-9535-11ea-8c68-d83921d96621.png)

**Comment by krlvm** [comment]
I confirm the wrong UI look on JRE11, it's GNOME-specific issue. The problem is this components are, actually, [locked JEditorPane](https://github.com/krlvm/PowerTunnel/blob/master/src/ru/krlvm/powertunnel/utilities/UIUtility.java#L42), because a regular JLabel doesn't support hyperlinks.

The app bar issue is also GNOME-specific. I have a solution and will push it in the next version.

**Comment by krlvm** [comment]
> I updated from version 8 to 11 yesterday.
> I've noticed an another UI issue - app bar name is invalid
> ![screen-130520-2](https://user-images.githubusercontent.com/59621052/81817562-91320080-9535-11ea-8c68-d83921d96621.png)

I highlighted this as a new issue
