### ISSUE TITLE
Not working in India

### ISSUE THREAD

**Issue by MrDisguised** [krlvm/PowerTunnel#147]
I am using this for like 3 - 4 months. It worked so well but now it is not working - 

When I try to go to nyaa.si , torrent websites and porn websites it shows me this - <br> 
![image](https://github.com/krlvm/PowerTunnel/assets/128170542/7852b558-5691-4a1e-a5d7-c03e7abc5be4)

Here is the recording - 
https://cdn.discordapp.com/attachments/1108295763160731720/1108295843024482365/recording.mp4

**Comment by krlvm** [comment]
This is not something that is possible to fix because, most likely your ISP upgraded filtration systems.

HTTP and HTTPS filtration is done in different ways, if you now have problems specifically with HTTP, you can enable tricks that add space or line break after GET (or any other HTTP method).

Since you are on Linux, you can try to use zapret, it has some advanced options which PowerTunnel does not have.
