### ISSUE TITLE
some idea about pass Internet censorship

### ISSUE THREAD

**Issue by arloor** [krlvm/PowerTunnel#23]
hello, I am the writer of https://github.com/arloor/HttpProxy. 

I found this project after you starred my project. As many people know, China government does Internet censorship for a long time. Many chinese developers have developed a lot of ways to pass it, like shadowsocks, v2ray, trojan and so on. My "Httpproxy" is one of them. 

I want to explain how my HttpProxy pass the censorship: encrypt any traffic over TLS.  We know https is "Http over TLS". My HttpProxy is "Http proxy over TLS".

httpproxy has a request called CONNECT。 http proxy over CONNECT encrypts every traffic over TLS, and when seeing inside, it looks like normal https requst to the SNI host。

For a long time， I want to write a android app which can pass china Internet censorship.  Maybe we can Cooperate to do this.

My telegram is https://t.me/popstarya. I wait for your reply. 

sorry for my poor English

**Comment by krlvm** [comment]
If I understand correctly, your proxy server re-crypts HTTPS traffic (which is already encrypted) under its own self-signed certificate and does a MITM attack by replacing the real SNI of the blocked site user want to connect to (e.g. `google.com`) with a fake one, that is not blocked (e.g. `gov.cn`).

PowerTunnel uses LittleProxy with MITM extension as a base proxy server for that purpose. This methods of censorship bypass already implemented in both Desktop and Android versions (I call them "SNI tricks").
LittleProxy is no longer maintained (the last build is 3 years old) and does not support some stuff of the modern web, so I'm looking for a replacement.

If you want to port your proxy server to Android, you just need to intercept the device traffic via VPNService and pass it through your proxy server, that should run locally on the device (VPN and proxy can be merged in one app).

Since this types of attack (and many others) is already implemented in PowerTunnel (written in Java like your project) and in other anticensorship utilities (GoodbyeDPI, zapret) you can contribute to the existing projects, including PowerTunnel, if you want.

Write if you have questions or want to cooperate on working on this project.
