### ISSUE TITLE
I turn off the server - the Internet stops working

### ISSUE THREAD

**Issue by FiveSeven123** [krlvm/PowerTunnel#56]
As soon as I turn off the server, my internet stops working. I reboot the modem - the internet still doesn't work. I close the program, restart the server - it doesn't matter. As soon as I turn off the server, the Internet does not work.

**Comment by krlvm** [comment]
PowerTunnel is a [proxy server](https://en.wikipedia.org/wiki/Proxy_server), which means that all your traffic goes to the Internet through it. If you're on Windows, when you start PowerTunnel, it configures itself automatically by setting the global system proxy server. When you stop PowerTunnel server, your system can't connect to the Internet because proxy server is missing in the chain. To disable system proxy server and restore normal Internet access, follow [this](https://www.windowsdigitals.com/disable-proxy-settings-windows-10-permanently/) manual.
